// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginRes struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Code     string `json:"code"`
	Gender   int    `json:"gender"`
	Avatar   string `json:"avatar"`
}

type RegisterRes struct {
}

type EmailSendReq struct {
	Email string `json:"email"`
}

type EmailSendRes struct {
}

type UpdateUserDetailReq struct {
	UserId int64  `json:"id"`
	Phone  string `json:"phone"`
	Gender int    `json:"gender"`
}

type UpdateUserDetailRes struct {
	Phone  string `json:"phone"`
	Gender int    `json:"gender"`
}

type GetUserDetailReq struct {
	UserId int64 `json:"id"`
}

type GetUserDetailRes struct {
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Email  string `json:"email"`
	Avatar string `json:"avatar"`
	Gender int    `json:"gender"`
}

type UpdateAvatarReq struct {
	UserId int64  `json:"id"`
	Avatar string `json:"avatar"`
}

type UpdateAvatarRes struct {
	Avatar string `json:"avatar"`
}

type ParentFolderIdReq struct {
	ParentFolderId int `path:"parentFolderId"`
}

type IdPathReq struct {
	Id int `path:"id"`
}

type FileTypeReq struct {
	FileType int `path:"fileType"`
}

type ListFolderMovableFolderReq struct {
	ParentFolderId    int   `json:"parentFolderId"`
	SelectedFolderIds []int `json:"selectedFolderIds"`
}

type MoveFilesReq struct {
	FolderId int `json:"folderId"`
	RecoverFilesReq
}

type MoveFoldersReq struct {
	FolderId int `json:"folderId"`
	RecoverFoldersReq
}

type UpdateFilesReq struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateFoldersReq struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type CopyFilesReq struct {
	FolderId int `path:"folderId"`
	RecoverFilesReq
}

type DeleteFilesReq struct {
	Ids []int `json:"ids"`
}

type DeleteFoldersReq struct {
	Ids []int `json:"ids"`
}

type RecoverFoldersReq struct {
	FolderIds []int `json:"folderIds"`
}

type RecoverFilesReq struct {
	FileIds []int `json:"fileIds"`
}

type CreateFoldersReq struct {
	Name           string `json:"name"`
	ParentFolderId int    `json:"parentFolderId"`
}

type FileRes struct {
	Id       int    `json:"id"`
	Name     string `json:"name"`
	Url      string `json:"url"`
	Status   int    `json:"status"`
	Size     int    `json:"size"`
	FolderId int    `json:"folderId,omitempty"`
	Created  string `json:"created"`
	Updated  string `json:"updated"`
}

type ListFolderRes struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	Updated string `json:"updated,omitempty"`
}

type ListDeleteItemsRes struct {
	Folders []*ListDeletedFolderStruct `json:"folders"`
	Files   []*ListDeletedFileStruct   `json:"files"`
}

type ListFolderStruct struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	Updated string `json:"updated,omitempty"`
}

type ListDeletedFolderStruct struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	DelTime int    `json:"delTime"`
}

type ListDeletedFileStruct struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	DelTime int    `json:"delTime"`
}
